language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install gfortran
install:
  - git clone https://github.com/steven-murray/pycamb.git
  - cd pycamb
  - python setup.py install --get=http://camb.info/CAMB.tar.gz
  - pip install numpy
  - pip install scipy
  - pip install scitools
  - pip install cosmolopy
  - pip install emcee
script: nosetests